add Linked List in English
TheAlgorithms/Swift pull request #12
Opened 2021-03-29 23:34 UTC by carloshmartins

This PR include a full implementation of Linked List

PS: Even is written in Swift, this implementation is not "Swift-ish", I mean that this implementation does not have Copy-or-Write performance and Swift Protocols, such as: Sequence and Collection for better performance.

2021-03-30 16:41 UTC, carloshmartins commented
@vbrazo Please, would you review my PR?

2021-03-30 17:57 UTC, vbrazo commented on data_structures/Linked List/LinkedList.swift
> +        node.next = node.next?.next
```suggestion
        if node.next === tail {
          tail = node 
        }
        node.next = node.next?.next
```

2021-03-30 18:09 UTC, vbrazo requested changes
Could you add some tests for your implementation? At least a few lines calling the classes so that we can reproduce the behavior in a playground.

The algorithms in this repository aren't using `XCTestCase` yet. I'd consider adding this in the long run and also link in the CI.

2021-03-30 23:06 UTC, carloshmartins commented
I added Linked List Test Scenario and DS Store into gitignore

2021-03-31 06:00 UTC, vbrazo approved these changes

2021-03-31 06:00 UTC, merged