Bubble sort algorithm added
TheAlgorithms/Swift pull request #18
Opened 2021-05-17 08:03 UTC by anantcodes

Added the bubble sort algorithm.

2021-05-18 14:29 UTC, anantcodes commented
@vbrazo Can you please review my PR?

2021-05-19 00:26 UTC, vbrazo requested changes
Hey - we need a test for your implementation. Please check other merged PRs out to see how people usually test.

2021-05-19 01:37 UTC, anantcodes commented
@vbrazo I have added a test.

2021-05-21 05:34 UTC, vbrazo approved these changes

2021-05-21 05:34 UTC, merged